In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# Store filepath in a variable
df = "Resources/trainCleaning.csv"

In [3]:
# Read our Data file with the pandas library
# Not every CSV requires an encoding, but be aware this can come up
df = pd.read_csv(df, encoding="ISO-8859-1")
# df_train = pd.read_csv(df_train, index_col=False, encoding="ISO-8859-1")

In [4]:
# Show just the header
df.head()

,Current Loan Amount,Term,Credit Scores,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Annual Debt,Debt to Income Ratio,...,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Utilization Rate Good/Bad,Utilization Rate,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
0,491,Short Term,NaN,1.0,Home Mortgage,NaN,Take a Trip,19.67,236.04,NaN,...,27.4,3,0,Excellent UR,0.04,43,1168,NaN,0.0,1
1,701,Short Term,718.0,1.0,Rent,19040.0,Debt Consolidation,196.74,2360.88,0.12,...,11.6,4,0,Very Bad UR,NaN,0,0,0.0,0.0,1
2,885,Short Term,731.0,3.0,Rent,11801.0,Educatiol Expenses,164.23,1970.76,0.17,...,14.4,4,0,Bad UR,0.66,3033,4623,NaN,0.0,0
3,975,Short Term,713.0,6.0,Rent,24378.0,Medical Bills,692.73,8312.76,0.34,...,7.1,10,0,Bad UR,0.60,4403,7313,0.0,0.0,1
4,975,Short Term,694.0,10.0,Home Mortgage,59599.0,Take a Trip,1157.22,13886.64,0.23,...,27.2,12,0,Bad UR,0.69,17869,25859,0.0,0.0,0

In [5]:
df.dtypes

Current Loan Amount            int64
Term                          object
Credit Scores                float64
Years in current job         float64
Home Ownership                object
Annual Income                float64
Purpose                       object
Monthly Debt                 float64
Annual Debt                  float64
Debt to Income Ratio         float64
Debt to Income Ratio G/B      object
Years of Credit History      float64
Number of Open Accounts        int64
Number of Credit Problems      int64
Utilization Rate Good/Bad     object
Utilization Rate             float64
Current Credit Balance         int64
Maximum Open Credit            int64
Bankruptcies                 float64
Tax Liens                    float64
Loan Status                    int64
dtype: object

In [6]:
df.fillna(df.mean(), inplace=True)
df.head(10)

<ipython-input-6-8ae6ea519571>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace=True)

,Current Loan Amount,Term,Credit Scores,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Annual Debt,Debt to Income Ratio,...,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Utilization Rate Good/Bad,Utilization Rate,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
0,491,Short Term,715.878187,1.0,Home Mortgage,72254.760527,Take a Trip,19.67,236.04,0.173108,...,27.4,3,0,Excellent UR,0.040000,43,1168,0.11448,0.0,1
1,701,Short Term,718.000000,1.0,Rent,19040.000000,Debt Consolidation,196.74,2360.88,0.120000,...,11.6,4,0,Very Bad UR,0.563226,0,0,0.00000,0.0,1
2,885,Short Term,731.000000,3.0,Rent,11801.000000,Educatiol Expenses,164.23,1970.76,0.170000,...,14.4,4,0,Bad UR,0.660000,3033,4623,0.11448,0.0,0
3,975,Short Term,713.000000,6.0,Rent,24378.000000,Medical Bills,692.73,8312.76,0.340000,...,7.1,10,0,Bad UR,0.600000,4403,7313,0.00000,0.0,1
4,975,Short Term,694.000000,10.0,Home Mortgage,59599.000000,Take a Trip,1157.22,13886.64,0.230000,...,27.2,12,0,Bad UR,0.690000,17869,25859,0.00000,0.0,0
5,976,Short Term,744.000000,10.0,Home Mortgage,66388.000000,other,1300.11,15601.32,0.240000,...,11.2,8,0,Excellent UR,0.280000,10707,37569,0.00000,0.0,1
6,976,Short Term,715.878187,10.0,Own Home,72254.760527,other,1691.21,20294.52,0.173108,...,26.4,6,0,Very Bad UR,1.000000,31281,31218,0.00000,0.0,1
7,976,Short Term,735.000000,6.0,Rent,71848.000000,Debt Consolidation,742.43,8909.16,0.120000,...,18.9,6,0,Very Bad UR,0.900000,9024,10060,0.00000,0.0,0
8,976,Short Term,720.000000,8.0,Home Mortgage,66368.000000,Debt Consolidation,1382.67,16592.04,0.250000,...,19.2,11,0,Very Bad UR,0.860000,33305,38547,0.00000,0.0,0
9,976,Short Term,683.000000,10.0,Rent,46824.000000,Other,924.77,11097.24,0.240000,...,22.0,13,0,Very Bad UR,0.780000,31614,40583,0.00000,0.0,1

In [7]:
df['Credit Scores'] = df['Credit Scores'].astype('int64')
df.head(10)

,Current Loan Amount,Term,Credit Scores,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Annual Debt,Debt to Income Ratio,...,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Utilization Rate Good/Bad,Utilization Rate,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
0,491,Short Term,715,1.0,Home Mortgage,72254.760527,Take a Trip,19.67,236.04,0.173108,...,27.4,3,0,Excellent UR,0.040000,43,1168,0.11448,0.0,1
1,701,Short Term,718,1.0,Rent,19040.000000,Debt Consolidation,196.74,2360.88,0.120000,...,11.6,4,0,Very Bad UR,0.563226,0,0,0.00000,0.0,1
2,885,Short Term,731,3.0,Rent,11801.000000,Educatiol Expenses,164.23,1970.76,0.170000,...,14.4,4,0,Bad UR,0.660000,3033,4623,0.11448,0.0,0
3,975,Short Term,713,6.0,Rent,24378.000000,Medical Bills,692.73,8312.76,0.340000,...,7.1,10,0,Bad UR,0.600000,4403,7313,0.00000,0.0,1
4,975,Short Term,694,10.0,Home Mortgage,59599.000000,Take a Trip,1157.22,13886.64,0.230000,...,27.2,12,0,Bad UR,0.690000,17869,25859,0.00000,0.0,0
5,976,Short Term,744,10.0,Home Mortgage,66388.000000,other,1300.11,15601.32,0.240000,...,11.2,8,0,Excellent UR,0.280000,10707,37569,0.00000,0.0,1
6,976,Short Term,715,10.0,Own Home,72254.760527,other,1691.21,20294.52,0.173108,...,26.4,6,0,Very Bad UR,1.000000,31281,31218,0.00000,0.0,1
7,976,Short Term,735,6.0,Rent,71848.000000,Debt Consolidation,742.43,8909.16,0.120000,...,18.9,6,0,Very Bad UR,0.900000,9024,10060,0.00000,0.0,0
8,976,Short Term,720,8.0,Home Mortgage,66368.000000,Debt Consolidation,1382.67,16592.04,0.250000,...,19.2,11,0,Very Bad UR,0.860000,33305,38547,0.00000,0.0,0
9,976,Short Term,683,10.0,Rent,46824.000000,Other,924.77,11097.24,0.240000,...,22.0,13,0,Very Bad UR,0.780000,31614,40583,0.00000,0.0,1

In [8]:
df['Years in current job'] = df['Years in current job'].astype('int64')
df['Annual Income'] = df['Annual Income'].astype('int64')
df['Bankruptcies'] = df['Bankruptcies'].astype('int64')
df['Tax Liens'] = df['Tax Liens'].astype('int64')
df['Debt to Income Ratio'] = df['Debt to Income Ratio'].astype('float64')
df['Utilization Rate'] = df['Utilization Rate'].astype('float64')

In [9]:
# df_train.info()
df.dtypes

Current Loan Amount            int64
Term                          object
Credit Scores                  int64
Years in current job           int64
Home Ownership                object
Annual Income                  int64
Purpose                       object
Monthly Debt                 float64
Annual Debt                  float64
Debt to Income Ratio         float64
Debt to Income Ratio G/B      object
Years of Credit History      float64
Number of Open Accounts        int64
Number of Credit Problems      int64
Utilization Rate Good/Bad     object
Utilization Rate             float64
Current Credit Balance         int64
Maximum Open Credit            int64
Bankruptcies                   int64
Tax Liens                      int64
Loan Status                    int64
dtype: object

In [10]:
df.head(20)

,Current Loan Amount,Term,Credit Scores,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Annual Debt,Debt to Income Ratio,...,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Utilization Rate Good/Bad,Utilization Rate,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
0,491,Short Term,715,1,Home Mortgage,72254,Take a Trip,19.67,236.04,0.173108,...,27.4,3,0,Excellent UR,0.040000,43,1168,0,0,1
1,701,Short Term,718,1,Rent,19040,Debt Consolidation,196.74,2360.88,0.120000,...,11.6,4,0,Very Bad UR,0.563226,0,0,0,0,1
2,885,Short Term,731,3,Rent,11801,Educatiol Expenses,164.23,1970.76,0.170000,...,14.4,4,0,Bad UR,0.660000,3033,4623,0,0,0
3,975,Short Term,713,6,Rent,24378,Medical Bills,692.73,8312.76,0.340000,...,7.1,10,0,Bad UR,0.600000,4403,7313,0,0,1
4,975,Short Term,694,10,Home Mortgage,59599,Take a Trip,1157.22,13886.64,0.230000,...,27.2,12,0,Bad UR,0.690000,17869,25859,0,0,0
5,976,Short Term,744,10,Home Mortgage,66388,other,1300.11,15601.32,0.240000,...,11.2,8,0,Excellent UR,0.280000,10707,37569,0,0,1
6,976,Short Term,715,10,Own Home,72254,other,1691.21,20294.52,0.173108,...,26.4,6,0,Very Bad UR,1.000000,31281,31218,0,0,1
7,976,Short Term,735,6,Rent,71848,Debt Consolidation,742.43,8909.16,0.120000,...,18.9,6,0,Very Bad UR,0.900000,9024,10060,0,0,0
8,976,Short Term,720,8,Home Mortgage,66368,Debt Consolidation,1382.67,16592.04,0.250000,...,19.2,11,0,Very Bad UR,0.860000,33305,38547,0,0,0
9,976,Short Term,683,10,Rent,46824,Other,924.77,11097.24,0.240000,...,22.0,13,0,Very Bad UR,0.780000,31614,40583,0,0,1
10,976,Short Term,715,1,Rent,72254,Debt Consolidation,266.72,3200.64,0.173108,...,20.7,6,0,Bad UR,0.590000,2751,4686,0,0,1
11,976,Short Term,718,10,Home Mortgage,59536,other,1215.53,14586.36,0.250000,...,27.1,14,0,Bad UR,0.540000,28791,53218,0,0,1
12,977,Short Term,726,5,Rent,17992,Other,89.96,1079.52,0.060000,...,23.3,3,1,Very Bad UR,0.840000,2453,2931,1,0,0
13,977,Short Term,740,10,Rent,43974,other,963.76,11565.12,0.260000,...,17.5,16,0,Excellent UR,0.270000,8500,31021,0,0,1
14,978,Short Term,720,8,Home Mortgage,30303,other,141.41,1696.92,0.060000,...,12.6,8,0,Good UR,0.310000,3471,11055,0,0,1
15,978,Short Term,750,1,Home Mortgage,104625,Home Improvements,83.70,1004.40,0.010000,...,18.0,20,0,Excellent UR,0.020000,4828,254125,0,0,1
16,978,Short Term,690,1,Rent,29817,Other,663.43,7961.16,0.270000,...,7.8,8,0,Good UR,0.490000,3332,6744,0,0,0
17,978,Short Term,686,10,Rent,54785,other,1223.53,14682.36,0.270000,...,14.1,14,0,Bad UR,0.540000,13828,25419,0,0,0
18,978,Short Term,680,5,Rent,39699,other,840.29,10083.48,0.250000,...,41.8,6,0,Bad UR,0.580000,4263,7401,0,0,1
19,979,Short Term,711,10,Rent,29367,Debt Consolidation,702.36,8428.32,0.290000,...,46.7,11,0,Very Bad UR,0.930000,14133,15181,0,0,1

In [11]:
df.isnull().sum(axis = 0)

Current Loan Amount           0
Term                          0
Credit Scores                 0
Years in current job          0
Home Ownership                0
Annual Income                 0
Purpose                       0
Monthly Debt                  0
Annual Debt                   0
Debt to Income Ratio          0
Debt to Income Ratio G/B     75
Years of Credit History       0
Number of Open Accounts       0
Number of Credit Problems     0
Utilization Rate Good/Bad    61
Utilization Rate              0
Current Credit Balance        0
Maximum Open Credit           0
Bankruptcies                  0
Tax Liens                     0
Loan Status                   0
dtype: int64

In [12]:
df.shape

(53407, 21)

In [13]:
df=df.dropna()

In [14]:
df.isnull().sum(axis=0)

Current Loan Amount          0
Term                         0
Credit Scores                0
Years in current job         0
Home Ownership               0
Annual Income                0
Purpose                      0
Monthly Debt                 0
Annual Debt                  0
Debt to Income Ratio         0
Debt to Income Ratio G/B     0
Years of Credit History      0
Number of Open Accounts      0
Number of Credit Problems    0
Utilization Rate Good/Bad    0
Utilization Rate             0
Current Credit Balance       0
Maximum Open Credit          0
Bankruptcies                 0
Tax Liens                    0
Loan Status                  0
dtype: int64

In [15]:
df.to_csv('df_train.csv', index=False)